# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163mKG-wQPxJxP6SnN3qC8GNEybe1FlyW
"""

from IPython.display import HTML

HTML('''
<!DOCTYPE html>
<html>
<head>
    <title>Login & Register</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to right, #4facfe, #00f2fe);
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            width: 300px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
        }

        h2 {
            text-align: center;
        }

        input {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            width: 100%;
            padding: 10px;
            background: #4facfe;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background: #007bff;
        }

        .message {
            text-align: center;
            margin-top: 10px;
            font-weight: bold;
        }

        .section {
            margin-bottom: 20px;
        }
    </style>
</head>

<body>

<div class="container">

    <div class="section">
        <h2>Register</h2>
        <input type="text" id="regUser" placeholder="Username">
        <input type="password" id="regPass" placeholder="Password">
        <button onclick="register()">Register</button>
    </div>

    <div class="section">
        <h2>Login</h2>
        <input type="text" id="logUser" placeholder="Username">
        <input type="password" id="logPass" placeholder="Password">
        <button onclick="login()">Login</button>
    </div>

    <p id="message" class="message"></p>

</div>

<script>
function register() {
    let username = document.getElementById("regUser").value;
    let password = document.getElementById("regPass").value;

    if (!username || !password) {
        showMessage("Please fill all fields", "red");
        return;
    }

    if (localStorage.getItem(username)) {
        showMessage("User already exists!", "red");
    } else {
        localStorage.setItem(username, password);
        showMessage("Registration successful!", "green");
    }
}

function login() {
    let username = document.getElementById("logUser").value;
    let password = document.getElementById("logPass").value;

    let storedPassword = localStorage.getItem(username);

    if (!storedPassword) {
        showMessage("User not found!", "red");
    } else if (storedPassword === password) {
        showMessage("Login successful!", "green");
    } else {
        showMessage("Wrong password!", "red");
    }
}

function showMessage(msg, color) {
    let message = document.getElementById("message");
    message.innerText = msg;
    message.style.color = color;
}
</script>

</body>
</html>
''')