# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163mKG-wQPxJxP6SnN3qC8GNEybe1FlyW
"""

from IPython.display import HTML

HTML('''
<!DOCTYPE html>
<html>
<head>
    <title>Login & Register</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to right, #4facfe, #00f2fe);
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background: white;
            padding: 30px;
            border-radius: 10px;
            width: 300px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
        }

        h2 {
            text-align: center;
        }

        input {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            width: 100%;
            padding: 10px;
            background: #4facfe;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background: #007bff;
        }

        .message {
            text-align: center;
            margin-top: 10px;
            font-weight: bold;
        }

        .section {
            margin-bottom: 20px;
        }
    </style>
</head>

<body>

<div class="container">

    <div class="section">
        <h2>Register</h2>
        <input type="text" id="regUser" placeholder="Username">
        <input type="password" id="regPass" placeholder="Password">
        <button onclick="register()">Register</button>
    </div>

    <div class="section">
        <h2>Login</h2>
        <input type="text" id="logUser" placeholder="Username">
        <input type="password" id="logPass" placeholder="Password">
        <button onclick="login()">Login</button>
    </div>

    <p id="message" class="message"></p>

</div>

<script>
function register() {
    let username = document.getElementById("regUser").value;
    let password = document.getElementById("regPass").value;

    if (!username || !password) {
        showMessage("Please fill all fields", "red");
        return;
    }

    if (localStorage.getItem(username)) {
        showMessage("User already exists!", "red");
    } else {
        localStorage.setItem(username, password);
        showMessage("Registration successful!", "green");
    }
}

function login() {
    let username = document.getElementById("logUser").value;
    let password = document.getElementById("logPass").value;

    let storedPassword = localStorage.getItem(username);

    if (!storedPassword) {
        showMessage("User not found!", "red");
    } else if (storedPassword === password) {
        showMessage("Login successful!", "green");
    } else {
        showMessage("Wrong password!", "red");
    }
}

function showMessage(msg, color) {
    let message = document.getElementById("message");
    message.innerText = msg;
    message.style.color = color;
}
</script>

</body>
</html>
''')

from IPython.display import HTML

HTML('''
<!DOCTYPE html>
<html>
<head>
    <title>Task Manager</title>
    <style>
        body {
            font-family: Arial;
            background: linear-gradient(to right, #4facfe, #00f2fe);
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background: white;
            padding: 20px;
            border-radius: 10px;
            width: 320px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
        }

        input {
            width: 100%;
            padding: 8px;
            margin: 5px 0;
        }

        button {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            background: #4facfe;
            color: white;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background: #007bff;
        }

        .hidden {
            display: none;
        }

        ul {
            padding: 0;
        }

        li {
            list-style: none;
            background: #f1f1f1;
            margin: 5px 0;
            padding: 8px;
            border-radius: 5px;
        }

        .message {
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>

<body>

<div class="container">

    <!-- AUTH SECTION -->
    <div id="authSection">
        <h3>Register</h3>
        <input type="text" id="regUser" placeholder="Username">
        <input type="password" id="regPass" placeholder="Password">
        <button onclick="register()">Register</button>

        <h3>Login</h3>
        <input type="text" id="logUser" placeholder="Username">
        <input type="password" id="logPass" placeholder="Password">
        <button onclick="login()">Login</button>
    </div>

    <!-- TASK SECTION -->
    <div id="taskSection" class="hidden">
        <h3>My Tasks</h3>
        <input type="text" id="taskInput" placeholder="Enter task">
        <button onclick="addTask()">Add Task</button>

        <ul id="taskList"></ul>

        <button onclick="logout()">Logout</button>
    </div>

    <p id="message" class="message"></p>

</div>

<script>
let currentUser = null;

// REGISTER
function register() {
    let username = regUser.value;
    let password = regPass.value;

    if (!username || !password) {
        showMessage("Fill all fields", "red");
        return;
    }

    if (localStorage.getItem("user_" + username)) {
        showMessage("User already exists", "red");
    } else {
        localStorage.setItem("user_" + username, password);
        localStorage.setItem("tasks_" + username, JSON.stringify([]));
        showMessage("Registered successfully", "green");
    }
}

// LOGIN
function login() {
    let username = logUser.value;
    let password = logPass.value;

    let storedPassword = localStorage.getItem("user_" + username);

    if (!storedPassword) {
        showMessage("User not found", "red");
    } else if (storedPassword === password) {
        currentUser = username;
        showMessage("Login successful", "green");
        showTasks();
    } else {
        showMessage("Wrong password", "red");
    }
}

// SHOW TASK UI
function showTasks() {
    authSection.classList.add("hidden");
    taskSection.classList.remove("hidden");
    loadTasks();
}

// ADD TASK
function addTask() {
    let task = taskInput.value;

    if (!task) return;

    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));
    tasks.push(task);

    localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));

    taskInput.value = "";
    loadTasks();
}

// LOAD TASKS
function loadTasks() {
    let taskList = document.getElementById("taskList");
    taskList.innerHTML = "";

    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));

    tasks.forEach((t) => {
        let li = document.createElement("li");
        li.textContent = t;
        taskList.appendChild(li);
    });
}

// LOGOUT
function logout() {
    currentUser = null;
    taskSection.classList.add("hidden");
    authSection.classList.remove("hidden");
    showMessage("Logged out", "blue");
}

// MESSAGE
function showMessage(msg, color) {
    let m = document.getElementById("message");
    m.innerText = msg;
    m.style.color = color;
}
</script>

</body>
</html>
''')

from IPython.display import HTML

HTML('''
<!DOCTYPE html>
<html>
<head>
    <title>Task Manager</title>
    <style>
        body {
            font-family: Arial;
            background: linear-gradient(to right, #4facfe, #00f2fe);
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background: white;
            padding: 20px;
            border-radius: 10px;
            width: 350px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
        }

        input {
            width: 100%;
            padding: 8px;
            margin: 5px 0;
        }

        button {
            padding: 8px;
            margin-top: 5px;
            background: #4facfe;
            color: white;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background: #007bff;
        }

        .hidden {
            display: none;
        }

        ul {
            padding: 0;
        }

        li {
            list-style: none;
            background: #f1f1f1;
            margin: 5px 0;
            padding: 8px;
            border-radius: 5px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .task-buttons button {
            margin-left: 5px;
            background: #6c757d;
        }

        .task-buttons button:hover {
            background: #343a40;
        }

        .message {
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>

<body>

<div class="container">

    <!-- AUTH -->
    <div id="authSection">
        <h3>Register</h3>
        <input type="text" id="regUser" placeholder="Username">
        <input type="password" id="regPass" placeholder="Password">
        <button onclick="register()">Register</button>

        <h3>Login</h3>
        <input type="text" id="logUser" placeholder="Username">
        <input type="password" id="logPass" placeholder="Password">
        <button onclick="login()">Login</button>
    </div>

    <!-- TASKS -->
    <div id="taskSection" class="hidden">
        <h3>My Tasks</h3>
        <input type="text" id="taskInput" placeholder="Enter task">
        <button onclick="addTask()">Add Task</button>

        <ul id="taskList"></ul>

        <button onclick="logout()">Logout</button>
    </div>

    <p id="message" class="message"></p>

</div>

<script>
let currentUser = null;

// REGISTER
function register() {
    let username = regUser.value;
    let password = regPass.value;

    if (!username || !password) {
        showMessage("Fill all fields", "red");
        return;
    }

    if (localStorage.getItem("user_" + username)) {
        showMessage("User already exists", "red");
    } else {
        localStorage.setItem("user_" + username, password);
        localStorage.setItem("tasks_" + username, JSON.stringify([]));
        showMessage("Registered successfully", "green");
    }
}

// LOGIN
function login() {
    let username = logUser.value;
    let password = logPass.value;

    let storedPassword = localStorage.getItem("user_" + username);

    if (!storedPassword) {
        showMessage("User not found", "red");
    } else if (storedPassword === password) {
        currentUser = username;
        showMessage("Login successful", "green");
        showTasks();
    } else {
        showMessage("Wrong password", "red");
    }
}

// SHOW TASK UI
function showTasks() {
    authSection.classList.add("hidden");
    taskSection.classList.remove("hidden");
    loadTasks();
}

// ADD TASK
function addTask() {
    let task = taskInput.value;

    if (!task) return;

    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));
    tasks.push(task);

    localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));

    taskInput.value = "";
    loadTasks();
}

// LOAD TASKS
function loadTasks() {
    let taskList = document.getElementById("taskList");
    taskList.innerHTML = "";

    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));

    tasks.forEach((t, index) => {
        let li = document.createElement("li");

        li.innerHTML = `
            <span>${t}</span>
            <div class="task-buttons">
                <button onclick="editTask(${index})">Edit</button>
                <button onclick="deleteTask(${index})">Delete</button>
            </div>
        `;

        taskList.appendChild(li);
    });
}

// EDIT TASK
function editTask(index) {
    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));
    let newTask = prompt("Edit your task:", tasks[index]);

    if (newTask !== null && newTask.trim() !== "") {
        tasks[index] = newTask;
        localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));
        loadTasks();
    }
}

// DELETE TASK
function deleteTask(index) {
    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));
    tasks.splice(index, 1);

    localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));
    loadTasks();
}

// LOGOUT
function logout() {
    currentUser = null;
    taskSection.classList.add("hidden");
    authSection.classList.remove("hidden");
    showMessage("Logged out", "blue");
}

// MESSAGE
function showMessage(msg, color) {
    let m = document.getElementById("message");
    m.innerText = msg;
    m.style.color = color;
}
</script>

</body>
</html>
''')

from IPython.display import HTML

HTML('''
<!DOCTYPE html>
<html>
<head>
    <title>Task Manager</title>
    <style>
        body {
            font-family: Arial;
            background: linear-gradient(to right, #4facfe, #00f2fe);
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background: white;
            padding: 20px;
            border-radius: 10px;
            width: 360px;
            box-shadow: 0 0 15px rgba(0,0,0,0.2);
        }

        input {
            width: 100%;
            padding: 8px;
            margin: 5px 0;
        }

        button {
            padding: 6px 8px;
            margin-top: 5px;
            background: #4facfe;
            color: white;
            border: none;
            cursor: pointer;
        }

        button:hover {
            background: #007bff;
        }

        .hidden {
            display: none;
        }

        ul {
            padding: 0;
        }

        li {
            list-style: none;
            background: #f1f1f1;
            margin: 5px 0;
            padding: 8px;
            border-radius: 5px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .completed {
            text-decoration: line-through;
            background: #d4edda;
        }

        .task-buttons button {
            margin-left: 4px;
            background: #6c757d;
        }

        .task-buttons button:hover {
            background: #343a40;
        }

        .message {
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>

<body>

<div class="container">

    <!-- AUTH -->
    <div id="authSection">
        <h3>Register</h3>
        <input type="text" id="regUser" placeholder="Username">
        <input type="password" id="regPass" placeholder="Password">
        <button onclick="register()">Register</button>

        <h3>Login</h3>
        <input type="text" id="logUser" placeholder="Username">
        <input type="password" id="logPass" placeholder="Password">
        <button onclick="login()">Login</button>
    </div>

    <!-- TASKS -->
    <div id="taskSection" class="hidden">
        <h3>My Tasks</h3>
        <input type="text" id="taskInput" placeholder="Enter task">
        <button onclick="addTask()">Add Task</button>

        <ul id="taskList"></ul>

        <button onclick="logout()">Logout</button>
    </div>

    <p id="message" class="message"></p>

</div>

<script>
let currentUser = null;

// REGISTER
function register() {
    let username = regUser.value;
    let password = regPass.value;

    if (!username || !password) {
        showMessage("Fill all fields", "red");
        return;
    }

    if (localStorage.getItem("user_" + username)) {
        showMessage("User already exists", "red");
    } else {
        localStorage.setItem("user_" + username, password);
        localStorage.setItem("tasks_" + username, JSON.stringify([]));
        showMessage("Registered successfully", "green");
    }
}

// LOGIN
function login() {
    let username = logUser.value;
    let password = logPass.value;

    let storedPassword = localStorage.getItem("user_" + username);

    if (!storedPassword) {
        showMessage("User not found", "red");
    } else if (storedPassword === password) {
        currentUser = username;
        showMessage("Login successful", "green");
        showTasks();
    } else {
        showMessage("Wrong password", "red");
    }
}

// SHOW TASK UI
function showTasks() {
    authSection.classList.add("hidden");
    taskSection.classList.remove("hidden");
    loadTasks();
}

// ADD TASK
function addTask() {
    let task = taskInput.value;

    if (!task) return;

    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));

    tasks.push({ text: task, completed: false });

    localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));

    taskInput.value = "";
    loadTasks();
}

// LOAD TASKS
function loadTasks() {
    let taskList = document.getElementById("taskList");
    taskList.innerHTML = "";

    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));

    tasks.forEach((t, index) => {
        let li = document.createElement("li");

        if (t.completed) {
            li.classList.add("completed");
        }

        li.innerHTML = `
            <span onclick="toggleComplete(${index})">${t.text}</span>
            <div class="task-buttons">
                <button onclick="editTask(${index})">Edit</button>
                <button onclick="deleteTask(${index})">Delete</button>
            </div>
        `;

        taskList.appendChild(li);
    });
}

// TOGGLE COMPLETE
function toggleComplete(index) {
    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));

    tasks[index].completed = !tasks[index].completed;

    localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));
    loadTasks();
}

// EDIT TASK
function editTask(index) {
    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));
    let newTask = prompt("Edit task:", tasks[index].text);

    if (newTask !== null && newTask.trim() !== "") {
        tasks[index].text = newTask;
        localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));
        loadTasks();
    }
}

// DELETE TASK
function deleteTask(index) {
    let tasks = JSON.parse(localStorage.getItem("tasks_" + currentUser));
    tasks.splice(index, 1);

    localStorage.setItem("tasks_" + currentUser, JSON.stringify(tasks));
    loadTasks();
}

// LOGOUT
function logout() {
    currentUser = null;
    taskSection.classList.add("hidden");
    authSection.classList.remove("hidden");
    showMessage("Logged out", "blue");
}

// MESSAGE
function showMessage(msg, color) {
    let m = document.getElementById("message");
    m.innerText = msg;
    m.style.color = color;
}
</script>

</body>
</html>
''')